function [T] = transformation_func(ceta_i,d_i,a_i,alpha_i)
T=[cosd(ceta_i),-sind(ceta_i)*cosd(alpha_i),sind(ceta_i)*sind(alpha_i),a_i*cosd(ceta_i);...
   sind(ceta_i),cosd(ceta_i)*cosd(alpha_i),-cosd(ceta_i)*sind(alpha_i),a_i*sind(ceta_i);...
              0,             sind(alpha_i),                cosd(alpha_i),           d_i;...
              0,                         0,                          0,               1];
end

